// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeD4VAxAiaiU1dGjsmZ_ggBJyMwaodPx8',
    appId: '1:717601755565:web:df912a1f215e59d3545124',
    messagingSenderId: '717601755565',
    projectId: 'flutternotesapp-268a3',
    authDomain: 'flutternotesapp-268a3.firebaseapp.com',
    storageBucket: 'flutternotesapp-268a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlBuJjBHsK8Qisml__mPtvmixn0IWy4n8',
    appId: '1:717601755565:android:94fc40f44ab716d8545124',
    messagingSenderId: '717601755565',
    projectId: 'flutternotesapp-268a3',
    storageBucket: 'flutternotesapp-268a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd3kDEwW6DZXfVqqcNZnGS9hmGPJtd-7M',
    appId: '1:717601755565:ios:99fc3726dc312765545124',
    messagingSenderId: '717601755565',
    projectId: 'flutternotesapp-268a3',
    storageBucket: 'flutternotesapp-268a3.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd3kDEwW6DZXfVqqcNZnGS9hmGPJtd-7M',
    appId: '1:717601755565:ios:99fc3726dc312765545124',
    messagingSenderId: '717601755565',
    projectId: 'flutternotesapp-268a3',
    storageBucket: 'flutternotesapp-268a3.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeD4VAxAiaiU1dGjsmZ_ggBJyMwaodPx8',
    appId: '1:717601755565:web:1a5f7d0e1350929c545124',
    messagingSenderId: '717601755565',
    projectId: 'flutternotesapp-268a3',
    authDomain: 'flutternotesapp-268a3.firebaseapp.com',
    storageBucket: 'flutternotesapp-268a3.firebasestorage.app',
  );
}
